// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Memastikan TypeScript menganggap URL ini sebagai string pasti
const databaseUrl = (process.env["DATABASE_URL"] || "") as string;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    /* @ts-ignore */
    url: databaseUrl,
  },
});